import { chromium } from 'playwright';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1600, height: 900 }, recordVideo: { dir: 'footage', size: { width: 1600, height: 900 } } });
const p = await ctx.newPage();
await p.goto('http://localhost:3000', { waitUntil: 'networkidle' });
await p.waitForTimeout(2500);
await p.getByRole('button', { name: 'Bhopal', exact: true }).click();
await p.waitForTimeout(4500);
await p.getByRole('button', { name: 'Investigate' }).click();
await p.waitForTimeout(9000);
await p.getByRole('button', { name: /Ingest broker brief/ }).click();
await p.waitForTimeout(3500);
await p.getByRole('button', { name: 'Project', exact: true }).click();
await p.waitForTimeout(1200);
await p.getByRole('button', { name: 'modular', exact: true }).click();
await p.waitForTimeout(3500);
await p.getByRole('button', { name: 'Compare' }).click();
await p.waitForTimeout(1200);
await p.getByRole('button', { name: 'Indore', exact: true }).click();
await p.waitForTimeout(3500);
await p.getByRole('button', { name: 'Compare' }).click();
await p.waitForTimeout(3500);
await ctx.close(); await b.close();
