import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1600, height: 900 } });
await p.goto('http://localhost:3000', { waitUntil: 'networkidle' });
await p.waitForTimeout(3000);
await p.getByRole('button', { name: 'Bhopal', exact: true }).click();
await p.waitForTimeout(4000);
await p.getByRole('button', { name: /Ingest broker brief/ }).click();
await p.waitForTimeout(2500);
await p.getByRole('button', { name: 'Project', exact: true }).click();
await p.waitForTimeout(800);
await p.screenshot({ path: 'shots/09a-project-tab.png' });
await p.getByRole('button', { name: 'modular', exact: true }).click();
await p.waitForTimeout(3500);
await p.screenshot({ path: 'shots/09-modular.png' });
await b.close();
